# Start with Windows
run_at_startup = true

# Don't remove default desktop
[[desktop_folder]]
name = "Default"
path = '%USERPROFILE%\Desktop'

# Examples:

# [[desktop_folder]]
# name = "Work"
# path = 'C:\Users\YourUsername\Desktop\Work'

# [[desktop_folder]]
# name = "Any folder can be a desktop!"
# path = 'C:\'

# Add as many as you wish
